"""new fields in user model

Revision ID: 382cdf58e1b5
Revises: 13674d151799
Create Date: 2018-09-28 20:05:00.633821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '382cdf58e1b5'
down_revision = '13674d151799'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
